### ISSUE TITLE
Thanks for the excellent job！

### ISSUE THREAD

**Issue by wener-yung** [GewelsJI/PNS-Net#4]
Thanks for the excellent job！ 
There is my questions: 
1. I am confused about the file PNS-Finetune.pth that you provide in the "Training/Testing" part. Whether it is the final weights or the pre-trained weights? 
2. Could you please explain the 'max' in the metrics 'maxDice', 'maxSpc' and 'maxIoU'？
3. I find something wrong in the file utils/dataloader.py, where the variate 'begin' is supposed to be set to 0 not 1 in class VideoDataset. The file MyTest_Finetune.py is the case. 
It would be very grateful if you could answer my questions.

**Comment by johnson111788** [comment]
Hi,

Thanks for your attention to our work. Here are the point-to-point answers:

1. `PNS-Finetune.pth` is the final weight.
2. You can refer to the original code in this [line](https://github.com/GewelsJI/PNS-Net/blob/9f80e6e30d34148fa2baa36cbbca4c5c413487ae/eval/main_VPS.m#L129)
3. During inference, we skip the first and the last frame in a video sequence since the evaluation metrics only compute the result started from t=1 to t=T-1 which is referring to [DAVIS](https://github.com/davisvideochallenge/davis-matlab/tree/davis-2016).

Best!

**Comment by wener-yung** [comment]
Thanks for answering!
I have tried you method on CVC-300 and CVC-612 datasets without pretraining, and I haven't skipped  the first and the last frame during inference. The experimental results can almost match your results in the paper.   Is my approach feasible？

**Comment by GewelsJI** [comment]
If you force to feed the first frame and last frame into the network, it may not change a lot according to my previous experience. You can post your result here, and we can make more discussions.

Thank you again,
Best regrads.
